### ISSUE TITLE
Mendix 9.24.3

### ISSUE THREAD

**Issue by Maudboomen** [j3lte/mendix-native-event-listener#1]
Dear Sir / Madam,

We use your native widget in our native application. However, we are not able to use it in Mendix 9.24.3 due to updated native template. We get the following error:

TypeError: t.DeviceEventEmitter.removeListener is not a function. (In 't.DeviceEventEmitter.removeListener(e.eventName,e.handler)', 't.DeviceEventEmitter.removeListener' is undefined)

This error is located at:
    in Unknown
    in h
    in pluginWidget()
    in RCTView
    in Unknown
    in P
    in P
    in h
    in pluginWidget(P)
    in Unknown
    in h
    in pluginWidget()
    in Unknown
    in h
    in pluginWidget()
    in Unknown
    in h
    in pluginWidget()
    in Unknown
    in h
    in pluginWidget()
    in Unknown
    in RCTView
    in Unknown
    in Gn
    in RCTView
    in Unknown
    in n
    in P
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in R
    in Unknown
    in PanGestureHandler
    in Unknown
    in RCTView
    in Unknown
    in R
    in Unknown
    in RCTView
    in Unknown
    in I
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in I
    in T
    in Unknown
    in RCTView
    in Unknown
    in w
    in Unknown
    in Unknown
    in k
    in P
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in S
    in RCTView
    in Unknown
    in s
    in RCTView
    in Unknown
    in _
    in P
    in k
    in P
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in R
    in Unknown
    in PanGestureHandler
    in Unknown
    in RCTView
    in Unknown
    in R
    in Unknown
    in RCTView
    in Unknown
    in I
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in I
    in T
    in Unknown
    in RCTView
    in Unknown
    in w
    in Unknown
    in Unknown
    in k
    in P
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in j
    in RCTView
    in Unknown
    in s
    in RCTView
    in Unknown
    in AnimatedComponent(View)
    in RCTView
    in Unknown
    in AnimatedComponent(View)
    in PanGestureHandler
    in oe
    in R
    in k
    in P
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in R
    in Unknown
    in PanGestureHandler
    in Unknown
    in RCTView
    in Unknown
    in R
    in Unknown
    in RCTView
    in Unknown
    in I
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in I
    in T
    in RNCSafeAreaProvider
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in w
    in Unknown
    in Unknown
    in k
    in E
    in RCTView
    in Unknown
    in Unknown
    in n
    in pr
    in i
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in b

The function is deprecated on the Mendix template used in Mendix 9.24.3. Due to react native template upgrade it is not working (https://github.com/facebook/react-native/issues/34644)
Could you please update this widget? This would help us a lot! :)

Thank you very much.

Kind regards,

Maud van den Boomen

P.S. I accidentally submitted an issue on the web widget, my appologies. I meant to send an issue for the native event listener, so hereby the ticket.

**Comment by j3lte** [comment]
Hi @Maudboomen,

I made a possible [bugfix](https://github.com/j3lte/mendix-native-event-listener/commit/de7d5e5511f9267e1c57cf3142aeab6d7d18e414) for this.

Could you download and test this version (1.0.1) for me: [-> Dropbox link <-](https://www.dropbox.com/s/pnmjmkwn1g5c0uw/caffcode.NativeEventListener.mpk?dl=0)? Haven't tested it myself, but looked at the issue you provided and changed the code accordingly.

**_Let me know if that fixes your issue. If so, I'll make an update for the Marketplace._**

**Comment by Maudboomen** [comment]
Hi Jelte,

Thank you very much for fixing this so quickly! This is very appreciated. 😄
I have added the widget to Mendix 9.24.3 and our functionality works as expected!
I have tested it on the make it native app and both IOS and Android builds.

Thanks again for fixing the issue.


Met vriendelijke groeten,

Maud van den Boomen

**Comment by j3lte** [comment]
[Version 1.0.1 is published](https://marketplace.mendix.com/link/component/202714)

Thanks for reporting the issue and testing the fix!
